app:
  name: GinGo
  version: v1.0.0
  addr: 0.0.0.0:8088
  env: main

mysql:
  host: 127.0.0.1
  port: 3306
  user: root
  password: 123456

redis:
  host: 127.0.0.1
  port: 6379

log:
  name: GinGo
  path: logs
  split: # 日志分割配置
    maxSize: 2 # 单文件最大容量,单位是MB
    maxAge: 30 # 保留过期文件的最大时间间隔,单位是天
    maxBackups: 128 # 最大保留的日志文件个数
    compress: false # 是否启用压缩